name: Release Phraser firmware

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow write access to repository contents

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you need

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Build the project
        run: |
          pio run

      - name: ls
        run: ls -al .pio

      - name: ls fw
        run: ls -al .pio/build/pico/

      - name: sha fw
        run: openssl sha256 .pio/build/pico/firmware*


