name: Release Phraser firmware

# This triggers workflow on tag push
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow write access to repository contents

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you need

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Build the project
        run: |
          pio run

      - name: ls
        run: ls -al .pio/build/pico/

      - name: sha256
        run: openssl sha256 .pio/build/pico/firmware*

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Phraser Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload firmware binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .pio/build/pico/firmware.uf2
          asset_name: firmware.uf2
          asset_content_type: application/binary

